### ISSUE TITLE
Use links

### ISSUE THREAD

**Issue by ghost** [tleyden/open-ocr#129]
https://github.com/tleyden/open-ocr/blob/3217ba41c9c8e308a0c9543f611814d17c2aa515/docker-compose/docker-compose.yml#L8

You can use "links" instead of always exposing the rabbitmq ports:
```
  # Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  # Start transformation worker
  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    command: "open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"

  # Start OCR worker
  openocrworker:
    image: tleyden5iwx/open-ocr-2
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    command: "open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: tleyden5iwx/open-ocr-2
    ports:
      - "9292:9292"
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    links:
      - rabbitmq
    command: "open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
````
